### ISSUE TITLE
movingaveragefilter?

### ISSUE THREAD

**Issue by jano2358** [sebnil/FIR_v2#1]
hi!

in examples you wrote the same code for your movingaveragefilter example!
what are the enhancements with respect to V1, BTW?
Thanks for make it public!

**Comment by sebnil** [comment]
Oh, maybe the example is wrong.. I have not touched this repo in a while. If you fix it, please create a pull request and I will probably merge it.
The enhancements to V1 I can't remember. Probably making it more generic.
